# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66f9e225cde9fb4811fa30a77453b7ec00a213460c76b40d94fda799c26baf0a432eadff72a1b00b5ecc42a164564450f5e11b7fe9ce660fba811f4d9411f7bb

test:
  secret_key_base: e072e466b3daf2ec9357e5fb574397a70b230c27cee13fd34ba2fbdb32314dd85c3068948f43eafcd027fe08688b93a6b62f286f95e247478109de59d1911b08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
